version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flozz_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=flozz_db
      - DB_PORT=3306
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  db_data:
