version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flozz_db
      MYSQL_USER: flozz
      MYSQL_PASSWORD: flozzpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
    image: flozz-backend:latest
    command: npm run dev
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: flozz
      DB_PASSWORD: flozzpass
      DB_NAME: flozz_db
      JWT_SECRET: supersecret
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    image: flozz-frontend:latest
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 3000
      REACT_APP_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
